/**
 * Tipo temporário para Pacientes até regeneração do types.ts
 */
export interface Patient {
  id: string;
  clinic_id: string;
  patient_code: string | null;
  full_name: string;
  social_name: string | null;
  cpf: string | null;
  rg: string | null;
  birth_date: string;
  gender: string | null;
  marital_status: string | null;
  nationality: string | null;
  occupation: string | null;
  education_level: string | null;
  email: string | null;
  phone_primary: string;
  phone_secondary: string | null;
  phone_emergency: string | null;
  emergency_contact_name: string | null;
  emergency_contact_relationship: string | null;
  address_street: string | null;
  address_number: string | null;
  address_complement: string | null;
  address_neighborhood: string | null;
  address_city: string | null;
  address_state: string | null;
  address_zipcode: string | null;
  address_country: string | null;
  has_systemic_disease: boolean | null;
  systemic_diseases: string[] | null;
  has_cardiovascular_disease: boolean | null;
  cardiovascular_details: string | null;
  has_diabetes: boolean | null;
  diabetes_type: string | null;
  diabetes_controlled: boolean | null;
  has_hypertension: boolean | null;
  hypertension_controlled: boolean | null;
  has_allergies: boolean | null;
  allergies_list: string[] | null;
  has_medication_allergy: boolean | null;
  medication_allergies: string[] | null;
  current_medications: string[] | null;
  has_bleeding_disorder: boolean | null;
  bleeding_disorder_details: string | null;
  is_pregnant: boolean | null;
  pregnancy_trimester: number | null;
  is_breastfeeding: boolean | null;
  has_hepatitis: boolean | null;
  hepatitis_type: string | null;
  has_hiv: boolean | null;
  has_smoking_habit: boolean | null;
  smoking_frequency: string | null;
  has_alcohol_habit: boolean | null;
  alcohol_frequency: string | null;
  blood_pressure_systolic: number | null;
  blood_pressure_diastolic: number | null;
  heart_rate: number | null;
  blood_type: string | null;
  weight_kg: number | null;
  height_cm: number | null;
  bmi: number | null;
  main_complaint: string | null;
  pain_level: number | null;
  clinical_observations: string | null;
  oral_hygiene_quality: string | null;
  gum_condition: string | null;
  risk_score_medical: number | null;
  risk_score_surgical: number | null;
  risk_score_anesthetic: number | null;
  risk_score_overall: number | null;
  risk_level: string | null;
  total_debt: number | null;
  total_paid: number | null;
  payment_status: string | null;
  preferred_payment_method: string | null;
  lgpd_consent: boolean | null;
  lgpd_consent_date: string | null;
  image_usage_consent: boolean | null;
  treatment_consent: boolean | null;
  data_sharing_consent: boolean | null;
  status: string | null;
  first_appointment_date: string | null;
  last_appointment_date: string | null;
  total_appointments: number | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}
